name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # ✅ Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # ✅ Log in to Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    # ✅ Build and push Docker image
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/login-chat:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/login-chat:latest

    # ✅ Set up SSH key
    - name: Setup SSH key
      run: |
        echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ~/.ssh/gcp_ecdsa_key
        chmod 600 ~/.ssh/gcp_ecdsa_key
        ssh-keyscan -H ${{ secrets.GCP_VM_IP }} >> ~/.ssh/known_hosts

    # ✅ Deploy on GCP VM
    - name: Deploy on GCP VM
      run: |
        ssh -i ~/.ssh/gcp_ecdsa_key ${{ secrets.GCP_VM_USERNAME }}@${{ secrets.GCP_VM_IP }} << 'EOF'
          # Pull latest Docker image
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/login-chat:latest

          # Ensure MongoDB container is running
          docker start mongo || docker run -d --name mongo --network backend mongo

          # Stop and remove old login-chat container
          docker stop login-chat-server || true
          docker rm login-chat-server || true
          
          # Run new login-chat container with env variables
          docker run -d \
            --name login-chat-server \
            --restart always \
            --network backend \
            -p ${PORT_LOGIN_CHAT}:${PORT_LOGIN_CHAT} \
            -e PORT=${PORT_LOGIN_CHAT} \
            -e MONGO_URI=${MONGO_URI} \
            -e NODE_ENV=${NODE_ENV} \
            -e JWT_SECRET_KEY=${JWT_SECRET_KEY} \
            -e AWS_ACCESS_KEY=${AWS_ACCESS_KEY} \
            -e AWS_SECRET_KEY=${AWS_SECRET_KEY} \
            -e AWS_REGION=${AWS_REGION} \
            -e BUCKET_NAME=${BUCKET_NAME} \
            -e CLOUDFRONT_URL=${CLOUDFRONT_URL} \
            ${{ secrets.DOCKERHUB_USERNAME }}/login-chat:latest
        EOF
